CREATE TABLE CLIENTE(
	CDCLIENTE INT PRIMARY KEY NOT NULL,
	NOMECLIENTE VARCHAR(50)
)

CREATE TABLE PRODUTO(
	CDPRODUTO INT PRIMARY KEY NOT NULL,
	NOMEPRODUTO VARCHAR(20),
	QUANTIDADE INT,
	PRECOVENDA NUMERIC(7,2) 

)

CREATE TABLE VENDA(
	CDVENDA INT PRIMARY KEY NOT NULL,
	TOTAL NUMERIC(7,2),
	CDCLIENTE INT,
	FOREIGN KEY(CDCLIENTE) REFERENCES CLIENTE(CDCLIENTE),
	QUANTPARCE INT,
	PRAZOR VARCHAR(40),
	FORMAPARG VARCHAR(40),
	STATUS CHAR(2)
)

CREATE TABLE ITENSVENDA(
	CDITENSVENDA INT PRIMARY KEY NOT NULL,
	QUANT INT,
	PRECOVENDA NUMERIC(7,2),
	CDPRODUTO INT,
	CDVENDA INT,
	FOREIGN KEY(CDPRODUTO) REFERENCES PRODUTO(CDPRODUTO),
	FOREIGN KEY(CDVENDA) REFERENCES VENDA(CDVENDA)
)

